version: '3'

volumes:
  log_volume:
    driver: local


services:
  website:
    build: website
    restart: always
    env_file:
      - .docker.env
    ports:
      - '5000:8000'
    volumes:
      - 'log_volume:/home/node/log'

